using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Samirin33.AvatarEditor.Animation.Editor
{
    public static class VRCFaceTrackingParams
    {
        public static IReadOnlyList<AvatarParamDef> All { get; } = new List<AvatarParamDef>
        {
            new AvatarParamDef("v2/EyeLeftX", AnimatorControllerParameterType.Float, false, "左目の左右視線。+で右、-で左。"),
            new AvatarParamDef("v2/EyeLeftY", AnimatorControllerParameterType.Float, false, "左目の上下視線。+で上、-で下。"),
            new AvatarParamDef("v2/EyeRightX", AnimatorControllerParameterType.Float, false, "右目の左右視線。+で右、-で左。"),
            new AvatarParamDef("v2/EyeRightY", AnimatorControllerParameterType.Float, false, "右目の上下視線。+で上、-で下。"),
            new AvatarParamDef("v2/EyeLidRight", AnimatorControllerParameterType.Float, false, "右まぶたの開閉/見開き。"),
            new AvatarParamDef("v2/EyeLidLeft", AnimatorControllerParameterType.Float, false, "左まぶたの開閉/見開き。"),
            new AvatarParamDef("v2/EyeLid", AnimatorControllerParameterType.Float, false, "両まぶたの開閉/見開き。"),
            new AvatarParamDef("v2/EyeSquintRight", AnimatorControllerParameterType.Float, false, "右目の細め。"),
            new AvatarParamDef("v2/EyeSquintLeft", AnimatorControllerParameterType.Float, false, "左目の細め。"),
            new AvatarParamDef("v2/EyeSquint", AnimatorControllerParameterType.Float, false, "両目の細め。"),
            new AvatarParamDef("v2/PupilDilation", AnimatorControllerParameterType.Float, false, "瞳孔径の正規化値。"),
            new AvatarParamDef("v2/PupilDiameterRight", AnimatorControllerParameterType.Float, true, "右瞳孔径。"),
            new AvatarParamDef("v2/PupilDiameterLeft", AnimatorControllerParameterType.Float, true, "左瞳孔径。"),
            new AvatarParamDef("v2/PupilDiameter", AnimatorControllerParameterType.Float, true, "両瞳孔径。"),
            new AvatarParamDef("v2/BrowPinchRight", AnimatorControllerParameterType.Float, false, "右眉の寄せ。"),
            new AvatarParamDef("v2/BrowPinchLeft", AnimatorControllerParameterType.Float, false, "左眉の寄せ。"),
            new AvatarParamDef("v2/BrowLowererRight", AnimatorControllerParameterType.Float, false, "右眉の下げ。"),
            new AvatarParamDef("v2/BrowLowererLeft", AnimatorControllerParameterType.Float, false, "左眉の下げ。"),
            new AvatarParamDef("v2/BrowInnerUpRight", AnimatorControllerParameterType.Float, false, "右眉内側の上げ。"),
            new AvatarParamDef("v2/BrowInnerUpLeft", AnimatorControllerParameterType.Float, false, "左眉内側の上げ。"),
            new AvatarParamDef("v2/BrowOuterUpRight", AnimatorControllerParameterType.Float, false, "右眉外側の上げ。"),
            new AvatarParamDef("v2/BrowOuterUpLeft", AnimatorControllerParameterType.Float, false, "左眉外側の上げ。"),
            new AvatarParamDef("v2/NoseSneerRight", AnimatorControllerParameterType.Float, false, "右鼻のしかめ。"),
            new AvatarParamDef("v2/NoseSneerLeft", AnimatorControllerParameterType.Float, false, "左鼻のしかめ。"),
            new AvatarParamDef("v2/NasalDilationRight", AnimatorControllerParameterType.Float, false, "右鼻孔の拡張。"),
            new AvatarParamDef("v2/NasalDilationLeft", AnimatorControllerParameterType.Float, false, "左鼻孔の拡張。"),
            new AvatarParamDef("v2/NasalConstrictRight", AnimatorControllerParameterType.Float, false, "右鼻孔の収縮。"),
            new AvatarParamDef("v2/NasalConstrictLeft", AnimatorControllerParameterType.Float, false, "左鼻孔の収縮。"),
            new AvatarParamDef("v2/CheekSquintRight", AnimatorControllerParameterType.Float, false, "右頬の持ち上げ。"),
            new AvatarParamDef("v2/CheekSquintLeft", AnimatorControllerParameterType.Float, false, "左頬の持ち上げ。"),
            new AvatarParamDef("v2/CheekPuffSuckRight", AnimatorControllerParameterType.Float, false, "右頬の膨らみ/吸い込み。"),
            new AvatarParamDef("v2/CheekPuffSuckLeft", AnimatorControllerParameterType.Float, false, "左頬の膨らみ/吸い込み。"),
            new AvatarParamDef("v2/JawOpen", AnimatorControllerParameterType.Float, false, "あごの開き。"),
            new AvatarParamDef("v2/MouthClosed", AnimatorControllerParameterType.Float, false, "口閉じ。"),
            new AvatarParamDef("v2/JawX", AnimatorControllerParameterType.Float, false, "あごの左右移動。"),
            new AvatarParamDef("v2/JawZ", AnimatorControllerParameterType.Float, false, "あごの前後移動。"),
            new AvatarParamDef("v2/JawClench1", AnimatorControllerParameterType.Float, false, "あごの食いしばり。"),
            new AvatarParamDef("v2/JawMandibleRaise1", AnimatorControllerParameterType.Float, false, "下顎の持ち上げ。"),
            new AvatarParamDef("v2/LipSuckUpperRight", AnimatorControllerParameterType.Float, false, "右上唇の吸い込み。"),
            new AvatarParamDef("v2/LipSuckUpperLeft", AnimatorControllerParameterType.Float, false, "左上唇の吸い込み。"),
            new AvatarParamDef("v2/LipSuckLowerRight", AnimatorControllerParameterType.Float, false, "右下唇の吸い込み。"),
            new AvatarParamDef("v2/LipSuckLowerLeft", AnimatorControllerParameterType.Float, false, "左下唇の吸い込み。"),
            new AvatarParamDef("v2/LipSuckCornerRight", AnimatorControllerParameterType.Float, false, "右口角の吸い込み。"),
            new AvatarParamDef("v2/LipSuckCornerLeft", AnimatorControllerParameterType.Float, false, "左口角の吸い込み。"),
            new AvatarParamDef("v2/LipFunnelUpperRight", AnimatorControllerParameterType.Float, false, "右上唇のすぼめ。"),
            new AvatarParamDef("v2/LipFunnelUpperLeft", AnimatorControllerParameterType.Float, false, "左上唇のすぼめ。"),
            new AvatarParamDef("v2/LipFunnelLowerRight", AnimatorControllerParameterType.Float, false, "右下唇のすぼめ。"),
            new AvatarParamDef("v2/LipFunnelLowerLeft", AnimatorControllerParameterType.Float, false, "左下唇のすぼめ。"),
            new AvatarParamDef("v2/LipPuckerUpperRight", AnimatorControllerParameterType.Float, false, "右上唇の突き出し。"),
            new AvatarParamDef("v2/LipPuckerUpperLeft", AnimatorControllerParameterType.Float, false, "左上唇の突き出し。"),
            new AvatarParamDef("v2/LipPuckerLowerRight", AnimatorControllerParameterType.Float, false, "右下唇の突き出し。"),
            new AvatarParamDef("v2/LipPuckerLowerLeft", AnimatorControllerParameterType.Float, false, "左下唇の突き出し。"),
            new AvatarParamDef("v2/MouthUpperUpRight", AnimatorControllerParameterType.Float, false, "右上唇の上げ。"),
            new AvatarParamDef("v2/MouthUpperUpLeft", AnimatorControllerParameterType.Float, false, "左上唇の上げ。"),
            new AvatarParamDef("v2/MouthLowerDownRight", AnimatorControllerParameterType.Float, false, "右下唇の下げ。"),
            new AvatarParamDef("v2/MouthLowerDownLeft", AnimatorControllerParameterType.Float, false, "左下唇の下げ。"),
            new AvatarParamDef("v2/MouthUpperDeepenRight", AnimatorControllerParameterType.Float, false, "右上唇の深まり。"),
            new AvatarParamDef("v2/MouthUpperDeepenLeft", AnimatorControllerParameterType.Float, false, "左上唇の深まり。"),
            new AvatarParamDef("v2/MouthUpperX", AnimatorControllerParameterType.Float, false, "上唇の左右移動。"),
            new AvatarParamDef("v2/MouthLowerX", AnimatorControllerParameterType.Float, false, "下唇の左右移動。"),
            new AvatarParamDef("v2/MouthCornerPullRight", AnimatorControllerParameterType.Float, false, "右口角の引き上げ。"),
            new AvatarParamDef("v2/MouthCornerPullLeft", AnimatorControllerParameterType.Float, false, "左口角の引き上げ。"),
            new AvatarParamDef("v2/MouthCornerSlantRight", AnimatorControllerParameterType.Float, false, "右口角の斜め上げ。"),
            new AvatarParamDef("v2/MouthCornerSlantLeft", AnimatorControllerParameterType.Float, false, "左口角の斜め上げ。"),
            new AvatarParamDef("v2/MouthDimpleRight", AnimatorControllerParameterType.Float, false, "右えくぼ。"),
            new AvatarParamDef("v2/MouthDimpleLeft", AnimatorControllerParameterType.Float, false, "左えくぼ。"),
            new AvatarParamDef("v2/MouthFrownRight", AnimatorControllerParameterType.Float, false, "右口角の下げ。"),
            new AvatarParamDef("v2/MouthFrownLeft", AnimatorControllerParameterType.Float, false, "左口角の下げ。"),
            new AvatarParamDef("v2/MouthStretchRight", AnimatorControllerParameterType.Float, false, "右口角の横伸ばし。"),
            new AvatarParamDef("v2/MouthStretchLeft", AnimatorControllerParameterType.Float, false, "左口角の横伸ばし。"),
            new AvatarParamDef("v2/MouthRaiserUpper", AnimatorControllerParameterType.Float, false, "上唇中央の持ち上げ。"),
            new AvatarParamDef("v2/MouthRaiserLower", AnimatorControllerParameterType.Float, false, "下唇中央の持ち上げ。"),
            new AvatarParamDef("v2/MouthPressRight", AnimatorControllerParameterType.Float, false, "右口元の押し込み。"),
            new AvatarParamDef("v2/MouthPressLeft", AnimatorControllerParameterType.Float, false, "左口元の押し込み。"),
            new AvatarParamDef("v2/MouthTightenerRight", AnimatorControllerParameterType.Float, false, "右口元の引き締め。"),
            new AvatarParamDef("v2/MouthTightenerLeft", AnimatorControllerParameterType.Float, false, "左口元の引き締め。"),
            new AvatarParamDef("v2/TongueOut", AnimatorControllerParameterType.Float, false, "舌の突出。"),
            new AvatarParamDef("v2/TongueX", AnimatorControllerParameterType.Float, false, "舌の左右移動。"),
            new AvatarParamDef("v2/TongueY", AnimatorControllerParameterType.Float, false, "舌の上下移動。"),
            new AvatarParamDef("v2/TongueRoll", AnimatorControllerParameterType.Float, false, "舌のロール。"),
            new AvatarParamDef("v2/TongueArchY", AnimatorControllerParameterType.Float, false, "舌の反り/丸まり。"),
            new AvatarParamDef("v2/TongueShape", AnimatorControllerParameterType.Float, false, "舌形状（スクイッシュ/フラット）。"),
            new AvatarParamDef("v2/TongueTwistRight", AnimatorControllerParameterType.Float, false, "舌の右ねじり。"),
            new AvatarParamDef("v2/TongueTwistLeft", AnimatorControllerParameterType.Float, false, "舌の左ねじり。"),
            new AvatarParamDef("v2/SoftPalateClose", AnimatorControllerParameterType.Float, false, "軟口蓋の閉鎖。"),
            new AvatarParamDef("v2/ThroatSwallow", AnimatorControllerParameterType.Float, false, "喉の嚥下。"),
            new AvatarParamDef("v2/NeckFlexRight", AnimatorControllerParameterType.Float, false, "首の右側屈。"),
            new AvatarParamDef("v2/NeckFlexLeft", AnimatorControllerParameterType.Float, false, "首の左側屈。"),
            new AvatarParamDef("v2/EyeX", AnimatorControllerParameterType.Float, false, "両目の左右視線。"),
            new AvatarParamDef("v2/EyeY", AnimatorControllerParameterType.Float, false, "両目の上下視線。"),
            new AvatarParamDef("v2/BrowDownRight", AnimatorControllerParameterType.Float, false, "右眉下げ。"),
            new AvatarParamDef("v2/BrowDownLeft", AnimatorControllerParameterType.Float, false, "左眉下げ。"),
            new AvatarParamDef("v2/BrowOuterUp", AnimatorControllerParameterType.Float, false, "眉外側上げ。"),
            new AvatarParamDef("v2/BrowInnerUp", AnimatorControllerParameterType.Float, false, "眉内側上げ。"),
            new AvatarParamDef("v2/BrowUp", AnimatorControllerParameterType.Float, false, "眉上げ。"),
            new AvatarParamDef("v2/BrowExpressionRight", AnimatorControllerParameterType.Float, false, "右眉の上げ/下げ合成。"),
            new AvatarParamDef("v2/BrowExpressionLeft", AnimatorControllerParameterType.Float, false, "左眉の上げ/下げ合成。"),
            new AvatarParamDef("v2/BrowExpression", AnimatorControllerParameterType.Float, false, "両眉の上げ/下げ合成。"),
            new AvatarParamDef("v2/MouthX", AnimatorControllerParameterType.Float, false, "口全体の左右移動。"),
            new AvatarParamDef("v2/MouthUpperUp", AnimatorControllerParameterType.Float, false, "上唇上げ。"),
            new AvatarParamDef("v2/MouthLowerDown", AnimatorControllerParameterType.Float, false, "下唇下げ。"),
            new AvatarParamDef("v2/MouthOpen", AnimatorControllerParameterType.Float, false, "口開け（上唇+下唇）。"),
            new AvatarParamDef("v2/MouthSmileRight", AnimatorControllerParameterType.Float, false, "右笑顔。"),
            new AvatarParamDef("v2/MouthSmileLeft", AnimatorControllerParameterType.Float, false, "左笑顔。"),
            new AvatarParamDef("v2/MouthSadRight", AnimatorControllerParameterType.Float, false, "右悲しみ。"),
            new AvatarParamDef("v2/MouthSadLeft", AnimatorControllerParameterType.Float, false, "左悲しみ。"),
            new AvatarParamDef("v2/SmileFrownRight", AnimatorControllerParameterType.Float, false, "右笑顔/しかめ合成。"),
            new AvatarParamDef("v2/SmileFrownLeft", AnimatorControllerParameterType.Float, false, "左笑顔/しかめ合成。"),
            new AvatarParamDef("v2/SmileFrown", AnimatorControllerParameterType.Float, false, "笑顔/しかめ合成。"),
            new AvatarParamDef("v2/SmileSadRight", AnimatorControllerParameterType.Float, false, "右笑顔/悲しみ合成。"),
            new AvatarParamDef("v2/SmileSadLeft", AnimatorControllerParameterType.Float, false, "左笑顔/悲しみ合成。"),
            new AvatarParamDef("v2/SmileSad", AnimatorControllerParameterType.Float, false, "両側笑顔/悲しみ合成。"),
            new AvatarParamDef("v2/LipSuckUpper", AnimatorControllerParameterType.Float, false, "上唇吸い込み。"),
            new AvatarParamDef("v2/LipSuckLower", AnimatorControllerParameterType.Float, false, "下唇吸い込み。"),
            new AvatarParamDef("v2/LipSuck", AnimatorControllerParameterType.Float, false, "唇吸い込み。"),
            new AvatarParamDef("v2/LipFunnelUpper", AnimatorControllerParameterType.Float, false, "上唇すぼめ。"),
            new AvatarParamDef("v2/LipFunnelLower", AnimatorControllerParameterType.Float, false, "下唇すぼめ。"),
            new AvatarParamDef("v2/LipFunnel", AnimatorControllerParameterType.Float, false, "唇すぼめ。"),
            new AvatarParamDef("v2/LipPuckerUpper", AnimatorControllerParameterType.Float, false, "上唇突き出し。"),
            new AvatarParamDef("v2/LipPuckerLower", AnimatorControllerParameterType.Float, false, "下唇突き出し。"),
            new AvatarParamDef("v2/LipPucker", AnimatorControllerParameterType.Float, false, "唇突き出し。"),
            new AvatarParamDef("v2/NoseSneer", AnimatorControllerParameterType.Float, false, "鼻しかめ。"),
            new AvatarParamDef("v2/CheekSquint", AnimatorControllerParameterType.Float, false, "頬の持ち上げ。"),
            new AvatarParamDef("v2/CheekPuffSuck", AnimatorControllerParameterType.Float, false, "頬の膨らみ/吸い込み。"),
            new AvatarParamDef("EyeTrackingActive", AnimatorControllerParameterType.Bool, true, "Eye Tracking モジュールが有効なら true。"),
            new AvatarParamDef("ExpressionTrackingActive", AnimatorControllerParameterType.Bool, true, "Expression Tracking モジュールが有効なら true。"),
            new AvatarParamDef("LipTrackingActive", AnimatorControllerParameterType.Bool, true, "Lip Tracking モジュールが有効なら true。"),
        };
    }
}
